// templates/nextjs/src/app/page.tsx
'use client'

import { useState } from 'react'
import { useFhevm, useEncrypt } from 'fhevm-sdk'

export default function Home() {
  const { ready, loading, error } = useFhevm()
  const { encrypt, encrypting } = useEncrypt()
  const [value, setValue] = useState('')
  const [result, setResult] = useState<string>('')

  const handleEncrypt = async () => {
    try {
      const encrypted = await encrypt(parseInt(value), 'uint32')
      const hex = '0x' + Array.from(encrypted.data)
        .map(b => b.toString(16).padStart(2, '0'))
        .join('')
      setResult(hex)
    } catch (err) {
      console.error('Encryption failed:', err)
    }
  }

  if (loading) return <div className="container">Loading FHEVM...</div>
  if (error) return <div className="container">Error: {error.message}</div>

  return (
    <main className="container">
      <h1>FHEVM Next.js Template</h1>
      <p>Status: {ready ? '✅ Ready' : '⏳ Initializing...'}</p>

      <div className="card">
        <h2>Encrypt a Value</h2>
        <input
          type="number"
          value={value}
          onChange={(e) => setValue(e.target.value)}
          placeholder="Enter a number"
          className="input"
        />
        <button
          onClick={handleEncrypt}
          disabled={!ready || encrypting || !value}
          className="button"
        >
          {encrypting ? 'Encrypting...' : 'Encrypt'}
        </button>

        {result && (
          <div className="result">
            <strong>Encrypted:</strong>
            <code>{result}</code>
          </div>
        )}
      </div>
    </main>
  )
}

// templates/vue/src/App.vue
<template>
  <div class="container">
    <h1>FHEVM Vue Template</h1>

    <div v-if="loading" class="loading">Loading FHEVM...</div>
    <div v-else-if="error" class="error">Error: {{ error.message }}</div>
    <div v-else>
      <p>Status: {{ ready ? '✅ Ready' : '⏳ Initializing...' }}</p>

      <div class="card">
        <h2>Encrypt a Value</h2>
        <input
          v-model="value"
          type="number"
          placeholder="Enter a number"
          class="input"
        />
        <button
          @click="handleEncrypt"
          :disabled="!ready || encrypting || !value"
          class="button"
        >
          {{ encrypting ? 'Encrypting...' : 'Encrypt' }}
        </button>

        <div v-if="result" class="result">
          <strong>Encrypted:</strong>
          <code>{{ result }}</code>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useFhevmComposable } from 'fhevm-sdk/vue'

const { instance, ready, loading, error, encrypt } = useFhevmComposable({
  network: 'sepolia'
})

const value = ref('')
const result = ref('')
const encrypting = ref(false)

const handleEncrypt = async () => {
  try {
    encrypting.value = true
    const encrypted = await encrypt(parseInt(value.value), 'uint32')
    const hex = '0x' + Array.from(encrypted.data)
      .map(b => b.toString(16).padStart(2, '0'))
      .join('')
    result.value = hex
  } catch (err) {
    console.error('Encryption failed:', err)
  } finally {
    encrypting.value = false
  }
}
</script>

<style>
@import './style.css';
</style>
